### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by jjk-g**
- Fix Header
- Move catalog.md link to top

### CODE REVIEW

**Comment by ahg-g** [comment]
@ArangoGutierrez did someone change the repo setting? we are getting `Merge type "merge" disallowed by repo settings` error

**Comment by jjk-g** [comment]
@ahg-g @terrytangyuan updated in https://github.com/kubernetes-sigs/wg-serving/pull/2#issuecomment-2297228676

**Comment by terrytangyuan** [comment]
What should the proper setting be to configure squash merge only?

**Comment by ahg-g** [comment]
> What should the proper setting be to configure squash merge only?

I am not sure, how did https://github.com/kubernetes-sigs/wg-serving/pull/7 get merged? did you force it?

**Comment by terrytangyuan** [comment]
I manually merged it. I can do that for this one too if needed.

**Comment by ahg-g** [comment]
> I manually merged it. I can do that for this one too if needed.

I think we need to reverse the setting to unblock us until we have this figured out.

**Review by terrytangyuan — APPROVED** [review]
Thanks!

/lgtm
/approve

**Comment by terrytangyuan** [comment]
Added the label so it should work in the futurr

**Pull request merged**
